### ISSUE TITLE
WHO TF DO U THINK U R!!!!!!!!!!

### ISSUE THREAD

**Issue by Hardwaregore** [AdoptMeTradingValues/AdoptMeTradingValues.github.io#1]
@AdoptMeTradingValues 
# WHO TF ARE YOU???? WHY DID YOU COPY MY STUFF?????? HOW DID YOU FIND MY GITHUB???? I CAN TELL THIS IS COPIED!!!!! YOU FORGOT TO REMOVE THE VS-CODE BOILERPLATE TEMPLATE!!!!!!! Y DIDN'T EVEN TRY TO MAKE THIS LOOK MORE COPIED!!!! STOP!!!!

**Comment by Hardwaregore** [comment]
# IF YOU DONT RESPOND TO THIS ISSUE BEFORE 12:12, THEM IM GOING TO REPORT YOU!!!

**Comment by 2C-P** [comment]
Hm, I am a hacker I do as I please your version sucked so I am making a true virus. And, if you think you can stop me you are very incorrect. I dont care if you report this it wont do anything and if it gets taken down. Well say goodbye to Hardwaregore.

**Comment by Hardwaregore** [comment]
you suck

**Comment by Hardwaregore** [comment]
i wasted like 3 hours because of you

**Comment by Hardwaregore** [comment]
look at what you have done

**Comment by Hardwaregore** [comment]
![suspended](https://user-images.githubusercontent.com/88296644/191621545-c4737795-40c1-4f83-a898-47594eabc5b4.jpg)

**Comment by Hardwaregore** [comment]
this is the end. goodbye.

**Comment by 2C-P** [comment]
goodbye ;)

**Comment by TechDudie** [comment]
> Hm, I am a hacker I do as I please your version sucked so I am making a true virus. And, if you think you can stop me you are very incorrect. I dont care if you report this it wont do anything and if it gets taken down. Well say goodbye to Hardwaregore.

problem: then @Hardwaregore can call in the FBI and then you're a wanted criminal

or the law enforcement agency in your country at least
