### ISSUE TITLE
LOL, YOU COPIED MY CODE AGAIN AND IT DOESN'T WORK!!!!!!!

### ISSUE THREAD

**Issue by Hardwaregore** [AdoptMeTradingValues/AdoptMeTradingValues.github.io#2]
# LOLOLOLOLOLOLOLOLOLOLOLOLOLOLOOOLOLOLIO HAHAHAHAHAHAHAHAHAHAHAHAH YOU ARE AN IDIOT LOLOLOLOLLOOL

![Screen Shot 2022-09-24 at 2 51 44 PM](https://user-images.githubusercontent.com/88296644/192116091-c159ba77-9688-429f-a39e-3f67d9413502.png)

# UR IMAGE DOESN'T EVEN LOAD HAHAHAHAHAHAHAHAH LOLOLOLOLOLOLOL
 
# THE AUDIO DOESNT WORK EITHER!!!!!! HAHAHAHAHAHAH LOLOLOLOL

# THE POPUPS ARE BLOCKED!!!!!!!!

# YOU REALLY ARE AN IDIOT!!!!!

**Comment by Hardwaregore** [comment]
@AdoptMeTradingValues

**Comment by Hardwaregore** [comment]
![Screen Shot 2022-09-24 at 8 38 21 PM](https://user-images.githubusercontent.com/88296644/192124632-875993c6-fe3d-442f-b0b7-ced3d81e0bc7.png)
# AHAHAHAHAHAHAHHAHHAHHHAHAAAAAAAA LOLLLOLOLOLOLOLOOLOLLOLOOLOLLOLOLLOOLLOOLOLLOOLLOLLLLL XDXDXDDXDXDXDXDXDXDXDXDXXDXDXDXDXXDXDXDXXDX HAHAHAHHAHAAHAAHAHAHAHAHAHAHAHA LOLLOOLOLOLOLOLLOLOLOLLOOLLOOLOLOLOOLLLOOLOOOOLOLOLOLLOOLOLOLOLOLOLOLOLOLOOOOOOOLOLOLOOLOLLOLOLOLLOOOOOOOOOOOOOOOL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ÂHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁ

**Comment by Hardwaregore** [comment]
LOLOLOL YOU CHANGED UR SITE

**Comment by Hardwaregore** [comment]
I reported ur account

**Comment by Jmaxdnix1** [comment]
you want it to work il make it work

**Comment by Jmaxdnix1** [comment]
I've made a much better version if the trash  you thought was "good"

**Comment by Jmaxdnix1** [comment]
https://jmaxdnix1.github.io/

**Comment by Jmaxdnix1** [comment]
go to it lol

**Comment by Hardwaregore** [comment]
bruh the code is pirated lol!!!!!! I reconize it from youareanidiot.cc

**Comment by Hardwaregore** [comment]
also, 
> this is my new account because I'm using my github.io for another thing

means 'this is my new account because my old one got suspended'

**Comment by Hardwaregore** [comment]
anyways, i'm working on reverse engineering ur dumb pirated code

**Comment by TechDudie** [comment]
> ![Screen Shot 2022-09-24 at 8 38 21 PM](https://user-images.githubusercontent.com/88296644/192124632-875993c6-fe3d-442f-b0b7-ced3d81e0bc7.png)
> 
> # AHAHAHAHAHAHAHHAHHAHHHAHAAAAAAAA LOLLLOLOLOLOLOLOOLOLLOLOOLOLLOLOLLOOLLOOLOLLOOLLOLLLLL XDXDXDDXDXDXDXDXDXDXDXDXXDXDXDXDXXDXDXDXXDX HAHAHAHHAHAAHAAHAHAHAHAHAHAHAHA LOLLOOLOLOLOLOLLOLOLOLLOOLLOOLOLOLOOLLLOOLOOOOLOLOLOLLOOLOLOLOLOLOLOLOLOLOOOOOOOLOLOLOOLOLLOLOLOLLOOOOOOOOOOOOOOOL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ÂHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁ

uhhhh.... your MAC address is visible i think you should have blurred that out before insulting him a bunch of times

you aren't exactly the nicest person so other people wont be the nicest toward you also

**Comment by TechDudie** [comment]
@Hardwaregore

**Comment by Hardwaregore** [comment]
# @AdoptMeTradingValues LOL U GOT SUSPENDED!!!!!!!!!!!! AHAHAHAHAHAHAHHAHHAHHHAHAAAAAAAA LOLLLOLOLOLOLOLOOLOLLOLOOLOLLOLOLLOOLLOOLOLLOOLLOLLLLL XDXDXDDXDXDXDXDXDXDXDXDXXDXDXDXDXXDXDXDXXDX HAHAHAHHAHAAHAAHAHAHAHAHAHAHAHA LOLLOOLOLOLOLOLLOLOLOLLOOLLOOLOLOLOOLLLOOLOOOOLOLOLOLLOOLOLOLOLOLOLOLOLOLOOOOOOOLOLOLOOLOLLOLOLOLLOOOOOOOOOOOOOOOL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Hardwaregore** [comment]
# WHAT HAPPENED TO UR ALT ACCOUNT??????? HAHAHAHAHAHAAHAHAHAHAHAHAH XDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXDXD
